version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: main
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 20
    commit-message:
      prefix: 'deps'
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"