version: '3.9'
services:
  cuenta_unica:
    container_name: cuenta_unica
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SENTRY_ORG
        - SENTRY_PROJECT
        - SENTRY_AUTH_TOKEN
        - NEXT_PUBLIC_SENTRY_DSN
        - NEXT_PUBLIC_RECAPTCHA_SITE_KEY
    restart: unless-stopped
    networks:
      - cuenta_unica_network
    ports:
      - 3000:3000
    environment:
      - CEDULA_API
      - CEDULA_API_KEY
      - JCE_PHOTO_API
      - JCE_PHOTO_API_KEY
      - ENCRYPTION_KEY
      - RECAPTHA_API_KEY
      - RECAPTHA_PROJECT_ID
      - SITE_COOKIE_KEY
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY
      - NEXT_PUBLIC_GOOGLE_ANALYTICS
      - CEDULA_TOKEN_API
      - CITIZENS_API_AUTH_KEY
      - ORY_SDK_URL
      - NEXT_PUBLIC_ORY_SDK_URL
      - ORY_SDK_TOKEN
      - NEXT_PUBLIC_API_MOCKING
      - LIVENESS_THRESHOLD_VALUE
      - LIVENESS_SIMILARIY_VALUE
      - SENTRY_LOG_LEVEL=debug

networks:
  cuenta_unica_network: