name: Unit Tests

permissions: read-all

on:
  workflow_call:
    inputs:
      node_env:
        required: true
        type: string

  pull_request:
    branches:
      - master
    paths:
      - '**.js*'
      - '**.ts*'
      - package*.json
      - bun.lock
      - .github/workflows/ci-unit-tests.yml

  push:
    branches:
      - master
    paths:
      - '**.js*'
      - '**.ts*'
      - package*.json
      - bun.lock
      - .github/workflows/ci-unit-tests.yml

concurrency:
  # Ensures that only one workflow task will run at a time. Previous builds, if
  # already in process, will get cancelled. Only the latest commit will be allowed
  # to run, cancelling any workflows in between
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NODE_ENV: ${{ inputs.node_env }}
  NEXT_TELEMETRY_DISABLED: 1
  # we build a dev binary for use in CI so skip downloading
  # canary next-swc binaries in the monorepo
  NEXT_SKIP_NATIVE_POSTINSTALL: 1
  CI: true

jobs:
  test:
    name: Test with Bun
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Create AWS exports file
        run: echo "$AWS_EXPORTS_JSON" > src/aws-exports.js
        shell: bash
        env:
          AWS_EXPORTS_JSON: ${{secrets.AWS_EXPORTS_JSON}}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Audit for vulnerabilities
        run: bun audit

      - name: Run tests
        run: bun run test