name: Linting

on:
  push:
    branches:
      - "*"
    paths:
      - '**.js*'
      - '**.ts*'
      - 'package*.json'
      - '.github/workflows/lint-auth-registry-infra.yml'
  pull_request:
    branches:
      - "master"
    paths:
      - '**.js*'
      - '**.ts*'
      - 'package*.json'
      - '.github/workflows/lint-auth-registry-infra.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile
        env:
          NODE_ENV: development
      - name: Run linters
        if: github.event_name == 'push'
        uses: wearerequired/lint-action@v1
        with:
          auto_fix: true
          eslint: true
          prettier: false

      - name: Fail linting on push to PR
        if: github.event_name == 'pull_request'
        uses: wearerequired/lint-action@v1
        with:
          continue_on_error: false
          eslint: true
          prettier: false