name: Tests

on:
  workflow_call:
    inputs:
      node_env:
        required: true
        type: string

  pull_request:
    branches: ['master']
    paths:
      - '**.js*'
      - '**.ts*'
      - 'package*.json'
      - '.github/workflows/tests.yml'

  push:
    branches: ['master']
    paths:
      - '**.js*'
      - '**.ts*'
      - 'package*.json'
      - '.github/workflows/tests.yml'

concurrency:
  # Ensures that only one workflow task will run at a time. Previous builds, if
  # already in process, will get cancelled. Only the latest commit will be allowed
  # to run, cancelling any workflows in between
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NODE_ENV: ${{ inputs.node_env }}

jobs:
  test:
    name: Test with Node.js ${{ matrix.node }}
    timeout-minutes: 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['lts/*', 'latest']

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3.5.2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn test
